# 纯生产版本，一定先构建好
FROM node:14 as base
ENV GIT_REPO=https://github.com/awamwang/autojs-web-control.git \
  PROJECT_NAME=autojs-web-control

# install deps
FROM base as deps
WORKDIR /app/${PROJECT_NAME}
ADD ./server/package.json ./server/package-lock.json ./server/
ADD ./server/lib/ ./server/lib/
ADD ./web/package.json ./web/package-lock.json ./web/
RUN npm set progress=false
RUN cd /app/${PROJECT_NAME}/server && npm install --only=production --registry=https://registry.npmmirror.com \
  && cd /app/${PROJECT_NAME}/web && npm install --only=production --registry=https://registry.npmmirror.com \
  && npm install runjs chalk replace-in-file --registry=https://registry.npmmirror.com

# files
FROM deps as files
WORKDIR /app/${PROJECT_NAME}
COPY ./server/config/ ./server/config/
COPY ./web/vue.config.js ./web/
COPY ./web/src/settings.js ./web/src/
COPY ./web//mock/mock-server.js ./web/mock/
COPY docker/docker-entrypoint.sh .

# build
FROM files as build
COPY ./server/dist/ ./server/dist/
COPY ./web/build/ ./web/build
COPY ./web/dist/ ./web/dist/

# app
FROM build
WORKDIR /app/${PROJECT_NAME}
ENV DB_HOST=localhost \
  DB_PORT=3306 \
  DB_USER=root \
  DB_PASSWORD=123321 \
  DB_NAME=cloud_auto \
  DB_DEBUG=false \
  SERVER_LOG_LEVEL=DEBUG \
  VSCODE_EXT_PROXY_ON=false \
  VSCODE_EXT_IP=localhost \
  VSCODE_EXT_PORT=9317 \
  WEB_PORT=9528 \
  WEB_BASE_API=http://47.108.180.116:9319 \
  WEB_WS_HOST=ws://47.108.180.116:9319 \
  NODE_CONFIG_DIR=./config \
  SERVER_SECRET=xxx&T1G*sd3 \
  SERVER_EXPIRES_HOUR=6 \
  SERVER_SCRIPT_DIR=./scripts \
  CHOKIDAR_USEPOLLING=1 \
  SERVER_SCRIPT_POLLING_INTERVAL=10000
RUN chmod +x ./docker-entrypoint.sh
ENTRYPOINT [ "bash", "docker-entrypoint.sh" ]
# ENTRYPOINT ["echo", "Hello user"]
EXPOSE 9319
EXPOSE 9528
CMD [ "--server", "--web" ]

# docker build -t autojs-web-control -f docker/Dockerfile-prod .