version: "3"

# x-common: &common
#   image: autojs-web-control:latest
#   build:
#     context: .
#     dockerfile: ./Dockerfile
#   restart: always

# name: autojs-web-control # Added in version 3.4 file format.
services:
  awc-server:
    image: wangnew2013/autojs-web-control
    # image: autojs-web-control
    container_name: autojs-web-control-server
    command: ["--server"]
    env_file:
      - .env
    volumes:
      - ./data/server/config:/app/autojs-web-control/server/config
      - ./data/server/log:/app/autojs-web-control/server/log
      - ./data/server/scripts:/app/autojs-web-control/server/scripts
      - /etc/timezone:/etc/timezone
    ports:
      - 9319:9319 # Web UI
    restart: unless-stopped
  awc-web:
    image: wangnew2013/autojs-web-control
    # image: autojs-web-control
    container_name: autojs-web-control-web
    command: ["--web"]
    env_file:
      - .env
    # volumes:
    #   - /data/web/log:/web/log
    ports:
      - 9528:9528 # Web UI
    restart: unless-stopped

# docker-compose up -d