# x-common: &common
#   image: autojs-web-control:latest
#   build:
#     context: .
#     dockerfile: ./Dockerfile-prod
#   restart: always

# name: autojs-web-control # Added in version 3.4 file format.
services:
  awc-server:
    image: autojs-web-control
    container_name: autojs-web-control-server
    command: ["--server"]
    env_file:
      - .env
    volumes:
      - /etc/timezone:/etc/timezone
    ports:
      - 9319:9319 # Web UI
    restart: unless-stopped
  awc-web:
    image: autojs-web-control
    container_name: autojs-web-control-web
    command: ["--web"]
    env_file:
      - .env
    # volumes:
    #   - /data/web/log:/web/log
    ports:
      - 9528:9528 # Web UI
    restart: unless-stopped

# docker-compose --project-name "autojs-web-control" -f ./docker-compose.yml --project-directory ./ up -d --force-recreate