# x-common: &common
#   image: awc-run:latest
#   build:
#     context: .
#     dockerfile: ./Dockerfile
#   restart: always

# name: autojs-web-control # Added in version 3.4 file format.
services:
  awc-server:
    image: awc-run
    container_name: autojs-web-control-server
    networks:
      - awc_run_network 
    command: ["--server"]
    env_file:
      - .env
    volumes:
      - /etc/timezone:/etc/timezone
    ports:
      - 9319:9319 # Web UI
    restart: unless-stopped
  awc-web:
    image: awc-run
    container_name: autojs-web-control-web
    networks:
      - awc_run_network 
    command: ["--web"]
    env_file:
      - .env
    # volumes:
    #   - /data/web/log:/web/log
    ports:
      - 9528:9528 # Web UI
    restart: unless-stopped

networks:
  awc_run_network:
    external: true

# docker-compose --project-name "awc-run" -f ./docker-compose.yml --project-directory ./ up -d --force-recreate
